/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parse_579d3f85ddaed3f3bd9e01699b60566b/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parse_579d3f85ddaed3f3bd9e01699b60566b/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDrawer: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parse_579d3f85ddaed3f3bd9e01699b60566b/node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parse_579d3f85ddaed3f3bd9e01699b60566b/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parse_579d3f85ddaed3f3bd9e01699b60566b/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parse_579d3f85ddaed3f3bd9e01699b60566b/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parse_579d3f85ddaed3f3bd9e01699b60566b/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parse_579d3f85ddaed3f3bd9e01699b60566b/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parse_579d3f85ddaed3f3bd9e01699b60566b/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  }
}
