/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    DropdownMenu: typeof import('./components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./components/ui/select/SelectValue.vue')['default']
    Separator: typeof import('./components/ui/separator/Separator.vue')['default']
    Sheet: typeof import('./components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./components/ui/sheet/SheetHeader.vue')['default']
    SheetTitle: typeof import('./components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./components/ui/sheet/SheetTrigger.vue')['default']
    Switch: typeof import('./components/ui/switch/Switch.vue')['default']
    Tabs: typeof import('./components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./components/ui/tabs/TabsTrigger.vue')['default']
  }
}
